# Generated by rust2rpm 13
%bcond_without check
%global __cargo_skip_build 0

%global crate askalono-cli

Name:           rust-%{crate}
Version:        0.4.2
Release:        2%{?dist}
Summary:        Tool to detect the contents of license files

# cargo-license:
# Apache-2.0 (1): askalono
# Apache-2.0 AND BSD-2-Clause OR MIT (1): crossbeam-queue
# Apache-2.0 OR BSL-1.0 (1): ryu
# Apache-2.0 OR MIT (48): either, num-traits, backtrace-sys, rayon, crossbeam-epoch, cfg-if, 
# winapi-i686-pc-windows-gnu, backtrace, unicode-xid, serde_json, failure, env_logger, quote, 
# itoa, zstd-sys, rayon-core, unicode-normalization, cc, libc, num_cpus, autocfg, rustc-demangle, 
# regex, hermit-abi, semver-parser, lazy_static, serde, autocfg, serde_derive, crossbeam-utils, 
# log, smallvec, thread_local, jobserver, regex-syntax, quick-error, crossbeam-deque, winapi-
# x86_64-pc-windows-gnu, scopeguard, syn, semver, humantime, glob, winapi, rustc_version, 
# proc-macro2, zstd-safe, failure_derive
# MIT (6): zstd, rmp-serde, atty, rmp, synstructure, memoffset
# MIT OR Unlicense (5): winapi-util, termcolor, aho-corasick, byteorder, memchr
License:        ASL 2.0 and (ASL 2.0 or MIT and BSD) and (ASL 2.0 or Boost) and (ASL 2.0 or MIT) and MIT and (MIT or Unlicense)
URL:            https://crates.io/crates/askalono-cli
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Tool to detect the contents of license files.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc NOTICE README.md
%{_bindir}/askalono

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Jan 30 2020 Fedora Release Engineering <releng@fedoraproject.org> - 0.4.2-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_32_Mass_Rebuild

* Mon Jan 20 21:52:47 CET 2020 Robert-André Mauchin <zebob.m@gmail.com> - 0.4.2-1
- Update to 0.4.2
- Fix license to include all statically linked libraries

* Fri Jul 26 2019 Fedora Release Engineering <releng@fedoraproject.org> - 0.3.0-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild

* Sun Jul 21 10:17:13 CEST 2019 Igor Gnatenko <ignatenkobrain@fedoraproject.org> - 0.3.0-2
- Regenerate

* Thu Mar 28 12:56:20 CET 2019 Robert-André Mauchin <zebob.m@gmail.com> - 0.3.0-1
- Initial package
